AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create a CloudWatch alarm for EC2 CPU utilization   above 80%.

Resources:
  CpuUtilizationEc2Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ec2-cpu-utilizacao-alta
      AlarmDescription: >
        Alarme para detectar quando a utilização da CPU de uma instância EC2 ultrapassa 80%.
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: InstanceId
          Value: i-0da9d9d19c8f91ad3
      Statistic: Average
      Period: 300           # 5 minutos
      EvaluationPeriods: 2  # 2 períodos
      Threshold: 70.0
      ComparisonOperator: GreaterThanThreshold
      Unit: Percent
      # AlarmActions: []   # Removido, pois você não tem tópico SNS ainda
