name: Deploy CloudWatch Alarms

on:
  push:
    branches:
      - main
    paths:
      - 'alarms/**'
      - '.github/workflows/deploy_alarms.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::174590855898:role/GitHubActionsCloudFormationRole
          aws-region: us-east-2

      - name: Deploy CloudFormation stack (debug)
        run: |
          aws cloudformation deploy \
            --stack-name alarm_cpu_ec2 \
            --template-file alarms/alarm_cpu_ec2.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --debug
